# Copyright (c) 2026 stillgroup
# License: MIT
"""员工档案子表与扩展字段定义（由 patch / API 复用）。"""

from __future__ import annotations

CHILD_DOCTYPES = [
	{
		"name": "HR Emergency Contact",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "contact_name", "fieldtype": "Data", "label": "姓名", "reqd": 1, "in_list_view": 1},
			{"fieldname": "relationship", "fieldtype": "Data", "label": "与本人关系", "reqd": 1, "in_list_view": 1},
			{"fieldname": "mobile", "fieldtype": "Data", "label": "手机号码", "reqd": 1, "in_list_view": 1},
			{"fieldname": "workplace", "fieldtype": "Data", "label": "工作单位", "in_list_view": 1},
			{"fieldname": "address", "fieldtype": "Small Text", "label": "联系地址"},
		],
	},
	{
		"name": "HR Family Member",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "member_name", "fieldtype": "Data", "label": "姓名", "reqd": 1, "in_list_view": 1},
			{"fieldname": "relationship", "fieldtype": "Data", "label": "与本人关系", "reqd": 1, "in_list_view": 1},
			{"fieldname": "gender", "fieldtype": "Data", "label": "性别", "in_list_view": 1},
			{"fieldname": "date_of_birth", "fieldtype": "Date", "label": "出生日期"},
			{"fieldname": "mobile", "fieldtype": "Data", "label": "手机号码", "in_list_view": 1},
			{"fieldname": "workplace", "fieldtype": "Data", "label": "工作单位"},
			{"fieldname": "is_emergency_contact", "fieldtype": "Check", "label": "是否紧急联系人", "default": "0"},
		],
	},
	{
		"name": "HR Employee Contract",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{
				"fieldname": "contract_type",
				"fieldtype": "Select",
				"label": "合同类型",
				"reqd": 1,
				"in_list_view": 1,
				"options": "\n固定期限劳动合同\n无固定期限劳动合同\n实习协议\n劳务合同\n劳务派遣\n退休返聘\n其他",
			},
			{"fieldname": "contract_no", "fieldtype": "Data", "label": "合同编号", "reqd": 1, "in_list_view": 1},
			{"fieldname": "contract_company", "fieldtype": "Link", "label": "合同公司", "options": "Company", "reqd": 1, "in_list_view": 1},
			{"fieldname": "start_date", "fieldtype": "Date", "label": "合同开始日期", "reqd": 1, "in_list_view": 1},
			{"fieldname": "end_date", "fieldtype": "Date", "label": "合同结束日期", "in_list_view": 1},
			{"fieldname": "signed_date", "fieldtype": "Date", "label": "签订日期", "reqd": 1},
			{"fieldname": "probation_months", "fieldtype": "Data", "label": "试用期"},
			{
				"fieldname": "contract_status",
				"fieldtype": "Select",
				"label": "合同状态",
				"options": "\n未签订\n履行中\n已到期\n已解除\n已终止",
				"in_list_view": 1,
			},
			{
				"fieldname": "renewal_status",
				"fieldtype": "Select",
				"label": "续签状态",
				"options": "\n未续签\n已续签\n不续签",
			},
			{"fieldname": "attachment", "fieldtype": "Attach", "label": "合同附件"},
			{"fieldname": "remarks", "fieldtype": "Small Text", "label": "备注"},
		],
	},
	{
		"name": "HR Language Ability",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "language", "fieldtype": "Data", "label": "语言", "reqd": 1, "in_list_view": 1},
			{"fieldname": "listening", "fieldtype": "Data", "label": "听", "in_list_view": 1},
			{"fieldname": "speaking", "fieldtype": "Data", "label": "说", "in_list_view": 1},
			{"fieldname": "reading", "fieldtype": "Data", "label": "读"},
			{"fieldname": "writing", "fieldtype": "Data", "label": "写"},
			{"fieldname": "certificate", "fieldtype": "Data", "label": "证书"},
		],
	},
	{
		"name": "HR Work Skill",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "skill_name", "fieldtype": "Data", "label": "技能", "reqd": 1, "in_list_view": 1},
			{"fieldname": "level", "fieldtype": "Data", "label": "熟练度", "in_list_view": 1},
			{"fieldname": "years", "fieldtype": "Float", "label": "年限", "in_list_view": 1},
			{"fieldname": "remarks", "fieldtype": "Small Text", "label": "备注"},
		],
	},
	{
		"name": "HR Professional Title",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "title_name", "fieldtype": "Data", "label": "职称", "reqd": 1, "in_list_view": 1},
			{"fieldname": "level", "fieldtype": "Data", "label": "级别", "in_list_view": 1},
			{"fieldname": "issue_date", "fieldtype": "Date", "label": "获得日期", "in_list_view": 1},
			{"fieldname": "issuer", "fieldtype": "Data", "label": "发证单位"},
			{"fieldname": "attachment", "fieldtype": "Attach", "label": "附件"},
		],
	},
	{
		"name": "HR Certificate",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "certificate_name", "fieldtype": "Data", "label": "证书名称", "reqd": 1, "in_list_view": 1},
			{"fieldname": "certificate_no", "fieldtype": "Data", "label": "证书编号", "in_list_view": 1},
			{"fieldname": "issue_date", "fieldtype": "Date", "label": "发证日期", "in_list_view": 1},
			{"fieldname": "expire_date", "fieldtype": "Date", "label": "有效期至"},
			{"fieldname": "issuer", "fieldtype": "Data", "label": "发证单位"},
			{"fieldname": "attachment", "fieldtype": "Attach", "label": "附件"},
		],
	},
	{
		"name": "HR Training Record",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "training_name", "fieldtype": "Data", "label": "培训名称", "reqd": 1, "in_list_view": 1},
			{"fieldname": "organizer", "fieldtype": "Data", "label": "主办方", "in_list_view": 1},
			{"fieldname": "start_date", "fieldtype": "Date", "label": "开始日期", "in_list_view": 1},
			{"fieldname": "end_date", "fieldtype": "Date", "label": "结束日期"},
			{"fieldname": "hours", "fieldtype": "Float", "label": "学时"},
			{"fieldname": "result", "fieldtype": "Data", "label": "结果"},
			{"fieldname": "attachment", "fieldtype": "Attach", "label": "附件"},
		],
	},
	{
		"name": "HR Reward Punishment",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{
				"fieldname": "record_type",
				"fieldtype": "Select",
				"label": "类型",
				"reqd": 1,
				"in_list_view": 1,
				"options": "\n奖励\n惩罚",
			},
			{"fieldname": "title", "fieldtype": "Data", "label": "事项", "reqd": 1, "in_list_view": 1},
			{"fieldname": "occur_date", "fieldtype": "Date", "label": "发生日期", "in_list_view": 1},
			{"fieldname": "amount", "fieldtype": "Currency", "label": "金额"},
			{"fieldname": "remarks", "fieldtype": "Small Text", "label": "说明"},
			{"fieldname": "attachment", "fieldtype": "Attach", "label": "附件"},
		],
	},
	{
		"name": "HR Salary Adjustment",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "effective_date", "fieldtype": "Date", "label": "生效日期", "reqd": 1, "in_list_view": 1},
			{"fieldname": "salary_type", "fieldtype": "Data", "label": "薪资类型", "in_list_view": 1},
			{"fieldname": "base_salary", "fieldtype": "Currency", "label": "基本工资", "in_list_view": 1},
			{"fieldname": "position_salary", "fieldtype": "Currency", "label": "岗位工资"},
			{"fieldname": "performance_salary", "fieldtype": "Currency", "label": "绩效工资"},
			{"fieldname": "allowance", "fieldtype": "Currency", "label": "津贴/补贴"},
			{"fieldname": "remarks", "fieldtype": "Small Text", "label": "备注"},
		],
	},
	{
		"name": "HR Social Security Record",
		"module": "hr_roster",
		"istable": 1,
		"editable_grid": 1,
		"fields": [
			{"fieldname": "record_date", "fieldtype": "Date", "label": "记录日期", "reqd": 1, "in_list_view": 1},
			{
				"fieldname": "ss_status",
				"fieldtype": "Select",
				"label": "参保状态",
				"options": "\n未参保\n已参保\n停保",
				"in_list_view": 1,
			},
			{"fieldname": "ss_city", "fieldtype": "Data", "label": "参保城市", "in_list_view": 1},
			{"fieldname": "ss_base", "fieldtype": "Currency", "label": "社保基数"},
			{
				"fieldname": "hf_status",
				"fieldtype": "Select",
				"label": "公积金状态",
				"options": "\n未缴纳\n已缴纳\n停缴",
			},
			{"fieldname": "hf_city", "fieldtype": "Data", "label": "公积金城市"},
			{"fieldname": "hf_base", "fieldtype": "Currency", "label": "公积金基数"},
			{"fieldname": "remarks", "fieldtype": "Small Text", "label": "备注"},
		],
	},
]

# Employee 主表上的 Table 字段
TABLE_FIELDS = [
	{"fieldname": "hr_emergency_contacts", "label": "紧急联系人", "options": "HR Emergency Contact", "insert_after": "hr_wechat"},
	{"fieldname": "hr_family_members", "label": "家庭成员", "options": "HR Family Member", "insert_after": "hr_emergency_contacts"},
	{"fieldname": "hr_contracts", "label": "合同记录", "options": "HR Employee Contract", "insert_after": "hr_contract_remarks"},
	{"fieldname": "hr_languages", "label": "语言能力", "options": "HR Language Ability", "insert_after": "hr_weight"},
	{"fieldname": "hr_skills", "label": "工作技能", "options": "HR Work Skill", "insert_after": "hr_languages"},
	{"fieldname": "hr_titles", "label": "职称", "options": "HR Professional Title", "insert_after": "hr_skills"},
	{"fieldname": "hr_certificates", "label": "证书/证件", "options": "HR Certificate", "insert_after": "hr_titles"},
	{"fieldname": "hr_trainings", "label": "培训经历", "options": "HR Training Record", "insert_after": "hr_certificates"},
	{"fieldname": "hr_rewards", "label": "奖惩记录", "options": "HR Reward Punishment", "insert_after": "hr_probation_months"},
	{"fieldname": "hr_salary_history", "label": "工资调整记录", "options": "HR Salary Adjustment", "insert_after": "hr_housing_fund_base"},
	{"fieldname": "hr_ss_history", "label": "社保公积金记录", "options": "HR Social Security Record", "insert_after": "hr_salary_history"},
]

# 标量扩展字段
EXTRA_SCALAR_FIELDS = [
	{
		"fieldname": "hr_company_tenure_start",
		"fieldtype": "Date",
		"label": "司龄开始日期",
		"insert_after": "final_confirmation_date",
	},
	{
		"fieldname": "hr_leave_apply_date",
		"fieldtype": "Date",
		"label": "离职申请日期",
		"insert_after": "resignation_letter_date",
	},
	{
		"fieldname": "hr_last_working_day",
		"fieldtype": "Date",
		"label": "最后工作日",
		"insert_after": "hr_leave_apply_date",
	},
	{
		"fieldname": "hr_leave_type",
		"fieldtype": "Select",
		"label": "离职类型",
		"options": "\n主动离职\n协商解除\n公司辞退\n合同到期\n其他",
		"insert_after": "hr_last_working_day",
	},
	{
		"fieldname": "hr_leave_destination",
		"fieldtype": "Data",
		"label": "离职去向",
		"insert_after": "new_workplace",
	},
	{
		"fieldname": "hr_leave_remarks",
		"fieldtype": "Small Text",
		"label": "离职备注",
		"insert_after": "hr_leave_destination",
	},
	{
		"fieldname": "hr_ss_status",
		"fieldtype": "Select",
		"label": "社保参保状态",
		"options": "\n未参保\n已参保\n停保",
		"insert_after": "hr_social_insurance_section",
	},
	{
		"fieldname": "hr_ss_start_date",
		"fieldtype": "Date",
		"label": "社保开始日期",
		"insert_after": "hr_social_security_city",
	},
	{
		"fieldname": "hr_hf_status",
		"fieldtype": "Select",
		"label": "公积金缴纳状态",
		"options": "\n未缴纳\n已缴纳\n停缴",
		"insert_after": "hr_ss_col_break",
	},
	{
		"fieldname": "hr_hf_city",
		"fieldtype": "Data",
		"label": "公积金缴纳城市",
		"insert_after": "hr_hf_status",
	},
	{
		"fieldname": "hr_hf_start_date",
		"fieldtype": "Date",
		"label": "公积金开始日期",
		"insert_after": "hr_hf_city",
	},
	{
		"fieldname": "hr_bank_city",
		"fieldtype": "Data",
		"label": "工资卡开户城市",
		"insert_after": "bank_name",
	},
	{
		"fieldname": "hr_bank_branch",
		"fieldtype": "Data",
		"label": "工资卡开户行",
		"insert_after": "hr_bank_city",
	},
	{
		"fieldname": "hr_salary_type",
		"fieldtype": "Data",
		"label": "薪资类型",
		"insert_after": "salary_mode",
	},
	{
		"fieldname": "hr_base_salary",
		"fieldtype": "Currency",
		"label": "基本工资",
		"insert_after": "hr_salary_type",
	},
	{
		"fieldname": "hr_position_salary",
		"fieldtype": "Currency",
		"label": "岗位工资",
		"insert_after": "hr_base_salary",
	},
	{
		"fieldname": "hr_performance_salary",
		"fieldtype": "Currency",
		"label": "绩效工资",
		"insert_after": "hr_position_salary",
	},
	{
		"fieldname": "hr_allowance",
		"fieldtype": "Currency",
		"label": "津贴/补贴",
		"insert_after": "hr_performance_salary",
	},
	{
		"fieldname": "hr_salary_effective_date",
		"fieldtype": "Date",
		"label": "薪资生效日期",
		"insert_after": "hr_allowance",
	},
	{
		"fieldname": "hr_salary_remarks",
		"fieldtype": "Small Text",
		"label": "薪资备注",
		"insert_after": "hr_salary_effective_date",
	},
	{
		"fieldname": "hr_wecom_id",
		"fieldtype": "Data",
		"label": "企业微信账号",
		"insert_after": "hr_wechat",
	},
	{
		"fieldname": "hr_work_phone",
		"fieldtype": "Data",
		"label": "工作电话",
		"insert_after": "company_email",
	},
	{
		"fieldname": "hr_probation_end",
		"fieldtype": "Date",
		"label": "试用期结束日期",
		"insert_after": "hr_probation_months",
	},
	{
		"fieldname": "hr_exam_period_section",
		"fieldtype": "Section Break",
		"label": "考察期信息",
		"insert_after": "hr_rewards",
	},
	{
		"fieldname": "hr_exam_start",
		"fieldtype": "Date",
		"label": "考察期开始",
		"insert_after": "hr_exam_period_section",
	},
	{
		"fieldname": "hr_exam_end",
		"fieldtype": "Date",
		"label": "考察期结束",
		"insert_after": "hr_exam_start",
	},
	{
		"fieldname": "hr_exam_result",
		"fieldtype": "Data",
		"label": "考察结果",
		"insert_after": "hr_exam_end",
	},
	{
		"fieldname": "hr_exam_remarks",
		"fieldtype": "Small Text",
		"label": "考察备注",
		"insert_after": "hr_exam_result",
	},
]

SECTION_FIELD_MAP = {
	"employment_basic": [
		"employee_number",
		"department",
		"hr_concurrent_post",
		"hr_job_title",
		"designation",
		"hr_position_category",
		"grade",
		"hr_job_grade_level",
		"company",
		"hr_employee_identity",
		"reports_to",
		"hr_work_location",
		"hr_work_city",
		"hr_work_address",
		"hr_work_hours_system",
		"hr_recruitment_channel",
		"attendance_device_id",
		"hr_oa_code",
		"branch",
		"group_name",
	],
	"employment_status": [
		"employment_type",
		"status",
		"date_of_joining",
		"hr_probation_months",
		"hr_probation_end",
		"scheduled_confirmation_date",
		"final_confirmation_date",
		"hr_company_tenure_start",
	],
	"employment_exit": [
		"hr_leave_apply_date",
		"hr_last_working_day",
		"relieving_date",
		"hr_leave_type",
		"reason_for_leaving",
		"hr_leave_destination",
		"hr_leave_remarks",
		"new_workplace",
		"resignation_letter_date",
	],
	"employment_exam": ["hr_exam_start", "hr_exam_end", "hr_exam_result", "hr_exam_remarks"],
	"employment_retire": ["date_of_retirement"],
	"personal_basic": [
		"employee_name",
		"first_name",
		"hr_alias",
		"hr_former_name",
		"hr_id_type",
		"hr_id_number",
		"hr_id_valid_until",
		"gender",
		"date_of_birth",
		"marital_status",
		"hr_has_children",
		"hr_country_region",
		"hr_ethnicity",
		"hr_political_status",
		"hr_native_place",
		"hr_household_city",
		"hr_household_type",
		"hr_household_address",
		"hr_social_security_household",
		"hr_work_start_date",
		"hr_height",
		"hr_weight",
		"health_details",
		"blood_group",
	],
	"contact_basic": [
		"cell_number",
		"personal_email",
		"hr_work_phone",
		"company_email",
		"current_address",
		"hr_wecom_id",
		"hr_wechat",
		"permanent_address",
	],
	"salary_bank": ["bank_ac_no", "bank_name", "hr_bank_city", "hr_bank_branch", "salary_mode", "iban"],
	"salary_ss": [
		"hr_ss_status",
		"hr_social_security_city",
		"hr_ss_start_date",
		"hr_social_security_base",
		"hr_social_security_no",
		"hr_hf_status",
		"hr_hf_city",
		"hr_hf_start_date",
		"hr_housing_fund_base",
		"hr_housing_fund_no",
	],
	"salary_pay": [
		"hr_salary_type",
		"hr_base_salary",
		"hr_position_salary",
		"hr_performance_salary",
		"hr_allowance",
		"hr_salary_effective_date",
		"hr_salary_remarks",
		"ctc",
		"salary_currency",
	],
	"contract_current": [
		"hr_contract_type",
		"hr_contract_status",
		"hr_contract_signed_date",
		"hr_contract_effective_from",
		"hr_contract_expire_date",
		"hr_contract_times",
		"hr_contract_remarks",
	],
	"materials": [
		"hr_attach_id_front",
		"hr_attach_id_back",
		"hr_attach_photo",
		"hr_attach_bank_card",
		"hr_attach_diploma",
		"hr_attach_degree",
		"hr_attach_resume",
		"hr_attach_resignation_proof",
		"hr_attach_medical_report",
		"hr_attach_others",
	],
	"overview_basic": [
		"employee_name",
		"first_name",
		"hr_id_number",
		"gender",
		"designation",
		"cell_number",
		"current_address",
		"status",
		"employee_number",
		"date_of_joining",
	],
	"overview_org": [
		"company",
		"department",
		"designation",
		"grade",
		"hr_work_location",
		"hr_work_city",
		"branch",
		"reports_to",
		"employment_type",
	],
	"attendance_settings": [
		"attendance_device_id",
		"holiday_list",
		"leave_approver",
		"expense_approver",
		"shift_request_approver",
	],
	"profile_bio": ["bio"],
	"background_basic": [
		"hr_background_status",
		"hr_background_agency",
		"hr_background_date",
		"hr_background_report",
		"hr_background_remarks",
	],
}

CHILD_TABLE_MAP = {
	"emergency_contacts": "hr_emergency_contacts",
	"family_members": "hr_family_members",
	"contracts": "hr_contracts",
	"languages": "hr_languages",
	"skills": "hr_skills",
	"titles": "hr_titles",
	"certificates": "hr_certificates",
	"trainings": "hr_trainings",
	"rewards": "hr_rewards",
	"salary_history": "hr_salary_history",
	"ss_history": "hr_ss_history",
	"education": "education",
	"external_work_history": "external_work_history",
	"internal_work_history": "internal_work_history",
}

REQUIRED_MATERIAL_KEYS = [
	"hr_attach_id_front",
	"hr_attach_id_back",
	"hr_attach_diploma",
	"hr_attach_photo",
	"hr_attach_resume",
]
